### ISSUE TITLE
'More tabs' dropdown for subreddit tab overflow displays incorrectly

### ISSUE THREAD

**Issue by TetraVisum** [KoffeinFlummi/alientube#21]
When there are too many subreddits to display tabs for, the 'More tabs' dropdown button will display. On clicking the button, a list of subrreddits appears. However the list appears too far to the right, and the subreddit names are cut off by overlapping elements and cannot be read.

![image](https://user-images.githubusercontent.com/17287172/45131470-35de3580-b1cc-11e8-80e0-b7a0a74aa023.png)

**Comment by TetraVisum** [comment]
The same dropdown is also cut off from below if the height of the comment area is shorter than the subreddit list.

Example:
![image](https://user-images.githubusercontent.com/17287172/45131701-51960b80-b1cd-11e8-88bd-fffc14d416da.png)

The same list but the comment area is big enough to show the rest of it:
![image](https://user-images.githubusercontent.com/17287172/45131753-899d4e80-b1cd-11e8-8113-d47564892665.png)

**Comment by draav** [comment]
Yep also can reproduce on the Chrome browser for my Mac and Windows machines:

Version 71.0.3578.98 (Official Build) (64-bit)

Screen recording of the issue and how adjusting the CSS resolves it partially, so it seems like just a styling problem:

![inline image](https://d2ddoduugvun08.cloudfront.net/items/0s0L0P3j3z1r293M1G2H/Screen%20Recording%202019-01-06%20at%2010.31%20PM.gif?X-CloudApp-Visitor-Id=3dabfe7741acf3f8fa6dc1fc64ace35c&v=4b0dd5aa)
https://cl.ly/dbbca0c99a1c

**Comment by draav** [comment]
Looks like this project hasn't been looked at or accepted PRs for 6 months. I'm too lazy to fork this so I used the [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en) Chrome extension to fix it. (there's probably some other styling extension that's better, this is just the first I found that works)

Here's the styling:

```
div.show ul {
    right: 150px;
}

#alientube {
    min-height: 1500px;
}
```

first one moves the dropdown to the right, second one increases the minimum size of the comments box to 1500, just to make sure the bottom of the drop down doesn't get cut off. There's probably some way to just push the drop down to the front, but idk CSS
