### ISSUE TITLE
Google+ comments not displaying, dark mode not working.

### ISSUE THREAD

**Issue by ImmortalFishy** [KoffeinFlummi/alientube#3]
Videos with no related Reddit pages are displaying nothing for Google+ comments, and videos with Reddit pages display nothing when the "switch to Google+" button is clicked. Clicking the checkbox to disable Alientube for that specific channel and reloading the page allows Google+ comments to be viewed. Also, the Reddit pages seem to be styled in the default white color as opposed to the new dark mode friendly black, when in dark mode on Youtube.

This doesn't seem to be the default behavior of the extension, and I haven't come across anyone with a similar issue, but no troubleshooting worked. Using different forks or just re-downloading the extension and re-enabling it again didn't solve anything either.

**Comment by 1j01** [comment]
I'm getting this and also it looks like the comments for the wrong video (one I had recently open):

![hmmmm](https://user-images.githubusercontent.com/3630663/32411381-7d9789a2-c1af-11e7-956b-76aa8853af87.png)

**Comment by ImmortalFishy** [comment]
I often get the same behavior as 1j01 mentioned, refreshing the page generally solves it, but it would be nice to know if there's a way to fix it.

**Comment by KoffeinFlummi** [comment]
This should be fixed.
