### ISSUE TITLE
Comments are removed when minimized

### ISSUE THREAD

**Issue by metherul** [KoffeinFlummi/alientube#5]
I'm not quite too sure if you're keeping track of this extension anymore, but here goes something. Comments (instead of being minimized at they should) are instead being removed from view. 

Before: https://i.imgur.com/a0B7PlI.png
After: https://i.imgur.com/HaOubk7.png

Running the SnooTube extension that you uploaded to the extension store, Chrome version 63.0.3239.40

I'd try to figure it out myself, but Javascript is an entirely new world to me. Sorry!

**Comment by KoffeinFlummi** [comment]
This should be fixed in the current version: https://github.com/KoffeinFlummi/alientube/releases

The version on the store wasn't uploaded by me.

**Comment by metherul** [comment]
Ah shoot, my bad! For some reason I thought you uploaded that. 

Anyways, thanks for the update!
